export type AudioSampleSource = "ago" | "a-nosa-fala" | "mapa-sonoro";

export interface AudioSample {
  id: string;
  comarcaCode: string;
  audioUrl: string;
  recordUrl: string;
  source: AudioSampleSource;
  sourceLabel: string;
  sourceRecord: string;
  municipality: string;
  locality: string;
  speaker: string;
  recordedAt: string;
  recorder: string;
  topic: string;
  clipStart: number;
  clipEnd: number;
  transcriptExcerpt: string;
}

const AGO_AUDIO_BASE = "https://ilg.usc.gal/ago/audios";
const AGO_RECORD_BASE = "https://ilg.usc.gal/ago/app/mod/doFichaHTML.php?id=";
const CCG_BASE = "https://mapasonoro.consellodacultura.gal";

type AgoSampleMetadata = Omit<
  AudioSample,
  | "id"
  | "audioUrl"
  | "recordUrl"
  | "source"
  | "sourceLabel"
  | "sourceRecord"
  | "transcriptExcerpt"
> & {
  transcriptExcerpt?: string;
};

function agoSample(audioId: number, metadata: AgoSampleMetadata): AudioSample {
  return {
    id: `ago-${String(audioId).padStart(3, "0")}`,
    audioUrl: `${AGO_AUDIO_BASE}/${audioId}.mp3`,
    recordUrl: `${AGO_RECORD_BASE}${audioId}`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: `Áudio ${audioId}`,
    transcriptExcerpt: "",
    ...metadata,
  };
}

/**
 * Curated pilot catalogue. Audio remains on the institutions' servers and the
 * player only exposes the selected interval until the answer is revealed.
 */
export const audioSamples: AudioSample[] = [
  {
    id: "ago-001",
    comarcaCode: "BAM",
    audioUrl: `${AGO_AUDIO_BASE}/1.mp3`,
    recordUrl: `${AGO_RECORD_BASE}1`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 1",
    municipality: "O Rosal",
    locality: "Fornelos, Santa Marinha do Rosal",
    speaker: "Homem, 64 anos",
    recordedAt: "1981",
    recorder: "Francisco Fernández Rei",
    topic: "A rendibilidade da terra",
    clipStart: 14,
    clipEnd: 42,
    transcriptExcerpt:
      "E iso era a falta que tínhamos nós aqui, neste recuncho. Antes estávamos no milho, e venha milho; depois começaram a pôr tomates.",
  },
  {
    id: "ago-076",
    comarcaCode: "MOR",
    audioUrl: `${AGO_AUDIO_BASE}/76.mp3`,
    recordUrl: `${AGO_RECORD_BASE}76`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 76",
    municipality: "Cangas",
    locality: "Cangas",
    speaker: "Homem, 80 anos",
    recordedAt: "1994",
    recorder: "X. M. Moldes Graña",
    topic: "O jogo do corno",
    clipStart: 0.9,
    clipEnd: 29,
    transcriptExcerpt:
      "O corno, o jogo do corno. Sabes como era? Colhias um corno de uma vaca e aquele a quem lhe tocava tinha que pôr a mão assim.",
  },
  {
    id: "ago-026",
    comarcaCode: "TCH",
    audioUrl: `${AGO_AUDIO_BASE}/26.mp3`,
    recordUrl: `${AGO_RECORD_BASE}26`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 26",
    municipality: "Cospeito",
    locality: "Xustás",
    speaker: "Mulher, 83 anos, lavradora",
    recordedAt: "1997",
    recorder: "María José Tejeda Pérez",
    topic: "A guerra e a pós-guerra",
    clipStart: 0,
    clipEnd: 28,
    transcriptExcerpt:
      "A minha vida foi muito pobre, porque acordei na pós-guerra. Foi o meu marido à guerra e passou muitos trabalhos; caiu duas vezes ferido.",
  },
  {
    id: "ago-061",
    comarcaCode: "TME",
    audioUrl: `${AGO_AUDIO_BASE}/61.mp3`,
    recordUrl: `${AGO_RECORD_BASE}61`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 61",
    municipality: "Melide",
    locality: "Melide",
    speaker: "Mulher, 74 anos",
    recordedAt: "1992",
    recorder: "Daniel Asorey Vidal",
    topic: "A fome e a vida familiar",
    clipStart: 0,
    clipEnd: 27,
    transcriptExcerpt:
      "Havia outro galopim de outro filho, que era sapateiro mas não trabalhava, que gastava os quartos. Uma vez havia que fazer uns vestidos aos rapazes.",
  },
  {
    id: "ago-119",
    comarcaCode: "MAR",
    audioUrl: `${AGO_AUDIO_BASE}/119.mp3`,
    recordUrl: `${AGO_RECORD_BASE}119`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 119",
    municipality: "Mondonhedo",
    locality: "Argomoso",
    speaker: "Mulher, 40 anos, lavradora",
    recordedAt: "1994",
    recorder: "Mario Romero Triñanes",
    topic: "Receita do caldo galego",
    clipStart: 1.1,
    clipEnd: 29,
    transcriptExcerpt:
      "Hoje fiz o caldo galego. Vou-te dizer como se faz. Deixei as favas de molho do dia anterior e pus a panela com as favas e o toucinho.",
  },
  {
    id: "ago-024",
    comarcaCode: "VDO",
    audioUrl: `${AGO_AUDIO_BASE}/24.mp3`,
    recordUrl: `${AGO_RECORD_BASE}24`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 24",
    municipality: "O Barco de Valdeorras",
    locality: "Alixo",
    speaker: "Homem, 76 anos, reformado",
    recordedAt: "1997",
    recorder: "Xabier Roo Abril e M. Docampo Paradelo",
    topic: "A guerra e a pós-guerra",
    clipStart: 0,
    clipEnd: 24,
    transcriptExcerpt:
      "Havia duas cantinas, dois bares. Tínhamos aqui o comércio de ultramarinos e em cima tínhamos o bar. Naquela altura havia muita gente.",
  },
  agoSample(153, {
    comarcaCode: "VIA",
    municipality: "Viana do Bolo",
    locality: "Caldesinhos",
    speaker: "Homem, 80 anos",
    recordedAt: "2006",
    recorder: "Concepción Álvarez Pousa",
    topic: "A mina",
    clipStart: 20,
    clipEnd: 45,
  }),
  {
    id: "ago-113",
    comarcaCode: "TNA",
    audioUrl: `${AGO_AUDIO_BASE}/113.mp3`,
    recordUrl: `${AGO_RECORD_BASE}113`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 113",
    municipality: "Taramundi",
    locality: "Cancelos de Arriba",
    speaker: "Rapaz, 12 anos, estudante",
    recordedAt: "2012",
    recorder: "Ana García García",
    topic: "As abelhas e o mel",
    clipStart: 0.7,
    clipEnd: 29,
    transcriptExcerpt:
      "Das abelhas sempre fui muito afeiçoado, porque o meu avô e o meu pai também eram, e sempre gostaram muito; eu hei de seguir a tradição.",
  },
  agoSample(141, {
    comarcaCode: "ARC",
    municipality: "Boimorto",
    locality: "Buazo, Santa María",
    speaker: "Mulher, 88 anos",
    recordedAt: "1993",
    recorder: "Isabel Felpete López",
    topic: "Regueifas e desafios",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(67, {
    comarcaCode: "ARN",
    municipality: "Xunqueira de Ambía",
    locality: "A Brandela",
    speaker: "Duas mulheres, 54 e 73 anos",
    recordedAt: "1993",
    recorder: "María Sánchez Cid",
    topic: "Entrudo",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(168, {
    comarcaCode: "BAL",
    municipality: "Lóvios",
    locality: "Torneiros, Santa María de Río Caldo",
    speaker: "Duas mulheres, 47 e 14 anos",
    recordedAt: "1995",
    recorder: "Isabel Villalba Seivane",
    topic: "A mata do porco",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(88, {
    comarcaCode: "BAR",
    municipality: "Boiro",
    locality: "Escarabote",
    speaker: "Mulher, 41 anos",
    recordedAt: "1994",
    recorder: "Ana M. Rubinos",
    topic: "Entrudo",
    clipStart: 58,
    clipEnd: 83,
  }),
  agoSample(54, {
    comarcaCode: "BER",
    municipality: "A Laracha",
    locality: "Estramil, Santa María de Torás",
    speaker: "Mulher, 23 anos, mestra",
    recordedAt: "1994",
    recorder: "Sandra Aldao Pereira",
    topic: "Repressão linguística",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(14, {
    comarcaCode: "BUR",
    municipality: "A Fonsagrada",
    locality: "Louxas",
    speaker: "Homem, 81 anos, soqueiro e lavrador",
    recordedAt: "1996",
    recorder: "Isabel Vázquez Vidal",
    topic: "A guerra civil e a pós-guerra",
    clipStart: 20,
    clipEnd: 45,
  }),
  {
    id: "ccg-1501",
    comarcaCode: "CAL",
    audioUrl: `${CCG_BASE}/files/peza/url/1501/ASG_SCSA_CD-0229_04.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/1501/2`,
    source: "mapa-sonoro",
    sourceLabel: "Cancioneiro popular galego — CCG / ASG",
    sourceRecord: "Peça 1501",
    municipality: "Cuntis",
    locality: "A Casiña, San Breixo de Arcos",
    speaker: "Duas mulheres, 70 e 62 anos, lavradoras",
    recordedAt: "entre 1978 e 1983",
    recorder: "Dorothé Schubarth",
    topic: "O carneiro e o gato",
    clipStart: 20,
    clipEnd: 45,
    transcriptExcerpt: "",
  },
  agoSample(73, {
    comarcaCode: "CAR",
    municipality: "O Carballiño",
    locality: "Arcos",
    speaker: "Mulher, 40 anos",
    recordedAt: "1996",
    recorder: "Carme Pérez González",
    topic: "Jogos tradicionais",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(58, {
    comarcaCode: "CEL",
    municipality: "Celanova",
    locality: "Carfaxiño",
    speaker: "Mulher, 17 anos, estudante",
    recordedAt: "1995",
    recorder: "María Carmen Trigo Estévez",
    topic: "Estudos",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(25, {
    comarcaCode: "CHA",
    municipality: "Chantada",
    locality: "A Santa Rosa",
    speaker: "Homem, 27 anos, lavrador",
    recordedAt: "1995",
    recorder: "Remedios López Argiz",
    topic: "A guerra civil e a pós-guerra",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(92, {
    comarcaCode: "COM",
    municipality: "Boqueixón",
    locality: "Ramil",
    speaker: "Homem, 50 anos",
    recordedAt: "1993",
    recorder: "Patricia Gómez Albela",
    topic: "Jogos tradicionais",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(80, {
    comarcaCode: "COR",
    municipality: "Abegondo",
    locality: "Vilar",
    speaker: "Mulher, 63 anos, lavradora",
    recordedAt: "1997",
    recorder: "María José Bermúdez Vázquez",
    topic: "Casamentos e despedidas",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(121, {
    comarcaCode: "COS",
    municipality: "Dumbría",
    locality: "Miñóns",
    speaker: "Mulher, 74 anos, lavradora",
    recordedAt: "1994",
    recorder: "Miro Villar González",
    topic: "Comidas",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(95, {
    comarcaCode: "COU",
    municipality: "Quiroga",
    locality: "Pacios da Serra",
    speaker: "Mulher, 50 anos",
    recordedAt: "1996",
    recorder: "Pilar Martínez Quiroga",
    topic: "Abelhas e mel",
    clipStart: 15,
    clipEnd: 39,
  }),
  agoSample(83, {
    comarcaCode: "DEC",
    municipality: "Rodeiro",
    locality: "Álceme, Santa María",
    speaker: "Duas mulheres, 63 e 25 anos",
    recordedAt: "1993",
    recorder: "M. Chamorro Díaz",
    topic: "O namoro",
    clipStart: 60,
    clipEnd: 85,
  }),
  agoSample(105, {
    comarcaCode: "EUM",
    municipality: "As Pontes de García Rodríguez",
    locality: "Trambasmeras, Santa María do Deveso",
    speaker: "Homem, 67 anos, lavrador",
    recordedAt: "1997",
    recorder: "Roberto García Fontao",
    topic: "Moinhos, fornos e pão",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(91, {
    comarcaCode: "LIM",
    municipality: "Os Blancos",
    locality: "Ouvigo",
    speaker: "Três mulheres, 24, 61 e 75 anos",
    recordedAt: "1993",
    recorder: "Diana Baltar López",
    topic: "Entrudo",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(126, {
    comarcaCode: "LUG",
    municipality: "Friol",
    locality: "Vilapedre",
    speaker: "Homem, 82 anos, lavrador",
    recordedAt: "1992",
    recorder: "A. Mª Carreira Varela",
    topic: "Lendas",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(138, {
    comarcaCode: "MAS",
    municipality: "Cesuras",
    locality: "O Xuaniño, San Pedro de Filgueira de Barranca",
    speaker: "Homem, 49 anos, lavrador",
    recordedAt: "1995",
    recorder: "Eduardo Moscoso Mato",
    topic: "O namoro",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(96, {
    comarcaCode: "MON",
    municipality: "Vilardevós",
    locality: "Arzoá",
    speaker: "Homem, 74 anos, lavrador",
    recordedAt: "1995",
    recorder: "Francisco X. Pérez Álvarez",
    topic: "Abelhas e mel",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(62, {
    comarcaCode: "MUR",
    municipality: "Muros",
    locality: "Muros",
    speaker: "Mulher, 20 anos",
    recordedAt: "2001",
    recorder: "Ana María Río Quintana",
    topic: "Emigração",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(135, {
    comarcaCode: "ORD",
    municipality: "Ordes",
    locality: "Os Lagos",
    speaker: "Homem, 73 anos, reformado",
    recordedAt: "1993",
    recorder: "Belén Lagares García",
    topic: "Namoro",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(98, {
    comarcaCode: "ORT",
    municipality: "Cedeira",
    locality: "A Ribeira",
    speaker: "Mulher, 86 anos, lavradora",
    recordedAt: "1993",
    recorder: "R. Romero Crego",
    topic: "Moinhos, fornos e pão",
    clipStart: 20,
    clipEnd: 45,
  }),
  {
    id: "ccg-436",
    comarcaCode: "OUR",
    audioUrl: `${CCG_BASE}/files/peza/url/436/cultura_popular_cd_2_20_a_cobra_e_o_leite.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/436/2`,
    source: "mapa-sonoro",
    sourceLabel: "A cultura popular de tradição oral — CCG",
    sourceRecord: "Peça 436",
    municipality: "A Peroxa",
    locality: "Os Peares, Nosa Señora do Pilar",
    speaker: "Carmen López Gómez",
    recordedAt: "1992",
    recorder: "Centro da Terceira Idade de Ourense / CCG",
    topic: "A cobra e o leite",
    clipStart: 5,
    clipEnd: 30,
    transcriptExcerpt: "",
  },
  agoSample(45, {
    comarcaCode: "PAR",
    municipality: "Crecente",
    locality: "O Mosteiro",
    speaker: "Homem, 63 anos, mineiro",
    recordedAt: "1994",
    recorder: "Xoán Carlos Ferreira Ambrosio",
    topic: "A mina",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(120, {
    comarcaCode: "PON",
    municipality: "Poio",
    locality: "Campelo",
    speaker: "Mulher, 60 anos, lavradora",
    recordedAt: "1996",
    recorder: "Raquel Martínez Casal",
    topic: "Comidas",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(118, {
    comarcaCode: "RIB",
    municipality: "A Arnoia",
    locality: "San Salvador da Arnoia",
    speaker: "Mulher, 61 anos",
    recordedAt: "1993",
    recorder: "A. Álvarez Castro",
    topic: "Comidas",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(41, {
    comarcaCode: "SAL",
    municipality: "Cambados",
    locality: "O Ribeiro",
    speaker: "Mulher, 77 anos, lavradora",
    recordedAt: "1996",
    recorder: "Raquel Oubiña Vázquez",
    topic: "A compaña",
    clipStart: 20,
    clipEnd: 45,
  }),
  {
    id: "ccg-386",
    comarcaCode: "SAR",
    audioUrl: `${CCG_BASE}/files/peza/url/386/a_nosa_fala_cd_2_11_varios_textos.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/386/2`,
    source: "a-nosa-fala",
    sourceLabel: "A nosa fala — CCG / ILG",
    sourceRecord: "Peça 386",
    municipality: "Triacastela",
    locality: "A Lagúa, San Isidro de Lamas",
    speaker: "Homem, 41 anos, lavrador",
    recordedAt: "dezembro de 1974",
    recorder: "Francisco Fernández Rei e Manuel González González",
    topic: "Vários textos",
    clipStart: 60,
    clipEnd: 85,
    transcriptExcerpt: "",
  },
  agoSample(173, {
    comarcaCode: "TAV",
    municipality: "Cerdedo",
    locality: "Cerdedelo",
    speaker: "Mulher, 74 anos, comerciante",
    recordedAt: "2000",
    recorder: "Teresa Cuíñas",
    topic: "Emigração",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(110, {
    comarcaCode: "TCA",
    municipality: "Montederramo",
    locality: "A Villeta",
    speaker: "Mulher, 76 anos, moleira",
    recordedAt: "1996",
    recorder: "Xabier Cid",
    topic: "O lobo",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(23, {
    comarcaCode: "TLE",
    municipality: "Monforte de Lemos",
    locality: "Piñeira",
    speaker: "Homem, 75 anos, reformado",
    recordedAt: "1994",
    recorder: "Mª X. Outes Velay",
    topic: "A guerra civil e a pós-guerra",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(13, {
    comarcaCode: "TMO",
    municipality: "Cotobade",
    locality: "A Chan",
    speaker: "Homem, 78 anos, marceneiro",
    recordedAt: "1994",
    recorder: "Ana Vidal",
    topic: "A mata do porco",
    clipStart: 25,
    clipEnd: 50,
  }),
  agoSample(68, {
    comarcaCode: "TTR",
    municipality: "A Pobra de Trives",
    locality: "A Pobra de Trives",
    speaker: "Homem, 45 anos",
    recordedAt: "1993",
    recorder: "Mónica Vidal Martínez",
    topic: "Entrudo",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(55, {
    comarcaCode: "TRA",
    municipality: "Ferrol",
    locality: "As Cruces, Brión",
    speaker: "Mulher, 57 anos",
    recordedAt: "1995",
    recorder: "S. Vidal e P. Vilaboi",
    topic: "Repressão linguística",
    clipStart: 18,
    clipEnd: 43,
  }),
  agoSample(79, {
    comarcaCode: "ULH",
    municipality: "Palas de Rei",
    locality: "O Carballal",
    speaker: "Homem, 51 anos, lavrador",
    recordedAt: "1993",
    recorder: "María Teresa Ulloa González",
    topic: "Jogos tradicionais",
    clipStart: 20,
    clipEnd: 45,
  }),
  agoSample(8, {
    comarcaCode: "VIG",
    municipality: "Vigo",
    locality: "San Salvador de Coruxo",
    speaker: "Mulher, 93 anos, reformada",
    recordedAt: "1992",
    recorder: "X. Anxo Terán Comesaña",
    topic: "A guerra civil e a pós-guerra",
    clipStart: 20,
    clipEnd: 45,
  }),
  {
    id: "ccg-385",
    comarcaCode: "ANC",
    audioUrl: `${CCG_BASE}/files/peza/url/385/a_nosa_fala_cd_2_10_vario_texos.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/385/2`,
    source: "a-nosa-fala",
    sourceLabel: "A nosa fala — CCG / ILG",
    sourceRecord: "Peça 385",
    municipality: "Candín",
    locality: "Pareda de Ancares",
    speaker: "Rapaz, 9 anos, estudante",
    recordedAt: "1984",
    recorder: "B. Arias Freixeiro e X. M. Gómez Clemente",
    topic: "Encontro com um javali",
    clipStart: 13.1,
    clipEnd: 37.1,
    transcriptExcerpt:
      "Fomos eu e outro menino a um pinhal e vimos um javali, uma fêmea com crias. Eu disse ao outro que fosse pelo lado de cima.",
  },
  {
    id: "ccg-388",
    comarcaCode: "SEA",
    audioUrl: `${CCG_BASE}/files/peza/url/388/a_nosa_fala_cd_2_13_varios_textos.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/388/2`,
    source: "a-nosa-fala",
    sourceLabel: "A nosa fala — CCG / ILG",
    sourceRecord: "Peça 388",
    municipality: "Lubián",
    locality: "Lubián",
    speaker: "Homem, aproximadamente 35 anos, professor",
    recordedAt: "1990",
    recorder: "M. A. Seixas para o programa As de ouros da TVG",
    topic: "O galego das Portelas",
    clipStart: 15,
    clipEnd: 43,
    transcriptExcerpt:
      "O galego desta zona é com toda a segurança diferente do galego que agora se está normativizando. Como falou o meu avô e falou o meu pai, eu seguirei falando sempre.",
  },
  {
    id: "ccg-379",
    comarcaCode: "CND",
    audioUrl: `${CCG_BASE}/files/peza/url/379/a_nosa_fala_cd_2_4_o_traballo_na_viña.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/379/2`,
    source: "a-nosa-fala",
    sourceLabel: "A nosa fala — CCG / ILG",
    sourceRecord: "Peça 379",
    municipality: "Mondariz",
    locality: "Lougares",
    speaker: "Homem, 62 anos, lavrador",
    recordedAt: "setembro de 1975",
    recorder: "M. González González",
    topic: "O trabalho na vinha",
    clipStart: 40,
    clipEnd: 65,
    transcriptExcerpt:
      "Para plantar a vinha há que fazer uma vala grande, pôr adubo e ramos de pinheiro, meter as cepas e cobri-las com terra.",
  },
  {
    id: "ccg-387",
    comarcaCode: "BEZ",
    audioUrl: `${CCG_BASE}/files/peza/url/387/a_nosa_fala_cd_2_12_a_construccion_do_apeadoiro.mp3`,
    recordUrl: `${CCG_BASE}/pezas/index/387/2`,
    source: "a-nosa-fala",
    sourceLabel: "A nosa fala — CCG / ILG",
    sourceRecord: "Peça 387",
    municipality: "Carucedo",
    locality: "A Barosa",
    speaker: "Homem, 72 anos, lavrador",
    recordedAt: "fevereiro de 1988",
    recorder: "F. Macías Macías",
    topic: "A construção do apeadeiro",
    clipStart: 180,
    clipEnd: 205,
    transcriptExcerpt:
      "Chegaram os chefes para medir, estaquilhar e preparar; a gente ficou contente e colaborou pessoalmente nos trabalhos.",
  },
];

// Kept outside the current rotation so already-published dates remain stable.
const legacyAudioSamples: AudioSample[] = [
  {
    id: "ago-149",
    comarcaCode: "VIA",
    audioUrl: `${AGO_AUDIO_BASE}/149.mp3`,
    recordUrl: `${AGO_RECORD_BASE}149`,
    source: "ago",
    sourceLabel: "Arquivo do Galego Oral — ILG",
    sourceRecord: "Áudio 149",
    municipality: "Viana do Bolo",
    locality: "Caldesinhos",
    speaker: "Homem, 80 anos",
    recordedAt: "2006",
    recorder: "Concepción Álvarez Pousa",
    topic: "As comparsas do Entrudo",
    clipStart: 0.7,
    clipEnd: 28,
    transcriptExcerpt:
      "Aqui faziam comparsas, talvez de dez ou quinze tipos. As mulheres também participavam, mas mais homens; alguns vestiam-se de mulher.",
  },
];

export function getAudioSampleById(id: string | null): AudioSample | undefined {
  if (!id) {
    return undefined;
  }

  return [...audioSamples, ...legacyAudioSamples].find(
    (sample) => sample.id === id
  );
}
